# Generated by Django 3.1.3 on 2020-11-30 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('w2dapi', '0003_todo_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='wut',
            new_name='task',
        ),
    ]
