# Generated by Django 3.1.3 on 2020-11-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w2dapi', '0004_auto_20201130_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
